export interface HotlistSuggestionRole {
  id: string;
  title: string;
  summary: string;
  minYearsExp: number;
  maxYearsExp: number;
  visaStatus: string;
  employmentType: string;
  workType: string;
  locations: string;
  minRate: number;
  maxRate: number;
  relocationOpen: boolean;
  skills: string;
  scheduleFrequency: 'disabled' | 'hourly' | 'daily' | 'twice_daily' | 'weekly';
}

export const HOTLIST_AI_SUGGESTIONS: HotlistSuggestionRole[] = [
  {
    id: 'senior-full-stack-engineer',
    title: 'Senior Full Stack Engineer',
    summary: 'Modern SaaS product engineering with React, Node.js, and cloud delivery.',
    minYearsExp: 6,
    maxYearsExp: 10,
    visaStatus: 'USC',
    employmentType: 'Full Time',
    workType: 'Remote',
    locations: 'New York, NY',
    minRate: 70,
    maxRate: 110,
    relocationOpen: true,
    skills: 'React, Node.js, AWS',
    scheduleFrequency: 'daily',
  },
  {
    id: 'backend-python-engineer',
    title: 'Backend Python Engineer',
    summary: 'API-heavy platform engineering with FastAPI and PostgreSQL.',
    minYearsExp: 4,
    maxYearsExp: 8,
    visaStatus: 'GC',
    employmentType: 'Full Time',
    workType: 'Hybrid',
    locations: 'Austin, TX',
    minRate: 65,
    maxRate: 100,
    relocationOpen: false,
    skills: 'Python, FastAPI, PostgreSQL',
    scheduleFrequency: 'daily',
  },
  {
    id: 'data-engineer',
    title: 'Data Engineer',
    summary: 'Analytics and data pipeline work with SQL, Spark, and Airflow.',
    minYearsExp: 5,
    maxYearsExp: 9,
    visaStatus: 'H1B',
    employmentType: 'Contract',
    workType: 'Remote',
    locations: 'Chicago, IL',
    minRate: 60,
    maxRate: 95,
    relocationOpen: true,
    skills: 'SQL, Spark, Airflow',
    scheduleFrequency: 'twice_daily',
  },
  {
    id: 'devops-engineer',
    title: 'DevOps Engineer',
    summary: 'Infrastructure reliability with AWS, Kubernetes, and Terraform.',
    minYearsExp: 3,
    maxYearsExp: 7,
    visaStatus: 'USC',
    employmentType: 'Full Time',
    workType: 'Onsite',
    locations: 'Dallas, TX',
    minRate: 62,
    maxRate: 90,
    relocationOpen: false,
    skills: 'AWS, Kubernetes, Terraform',
    scheduleFrequency: 'daily',
  },
  {
    id: 'qa-automation-engineer',
    title: 'QA Automation Engineer',
    summary: 'Fast-moving quality engineering for modern web products.',
    minYearsExp: 4,
    maxYearsExp: 8,
    visaStatus: 'GC',
    employmentType: 'Full Time',
    workType: 'Remote',
    locations: 'Seattle, WA',
    minRate: 55,
    maxRate: 85,
    relocationOpen: true,
    skills: 'Selenium, Playwright, Cypress',
    scheduleFrequency: 'weekly',
  },
  {
    id: 'product-manager',
    title: 'Product Manager',
    summary: 'Cross-functional product leadership for SaaS teams.',
    minYearsExp: 7,
    maxYearsExp: 12,
    visaStatus: 'USC',
    employmentType: 'Full Time',
    workType: 'Hybrid',
    locations: 'San Francisco, CA',
    minRate: 80,
    maxRate: 125,
    relocationOpen: true,
    skills: 'Roadmapping, Agile, Analytics',
    scheduleFrequency: 'daily',
  },
  {
    id: 'frontend-react-engineer',
    title: 'Frontend React Engineer',
    summary: 'High-quality frontend delivery with React, TypeScript, and UI polish.',
    minYearsExp: 3,
    maxYearsExp: 7,
    visaStatus: 'H4EAD',
    employmentType: 'Full Time',
    workType: 'Remote',
    locations: 'Denver, CO',
    minRate: 58,
    maxRate: 88,
    relocationOpen: false,
    skills: 'React, TypeScript, Tailwind',
    scheduleFrequency: 'hourly',
  },
  {
    id: 'machine-learning-engineer',
    title: 'Machine Learning Engineer',
    summary: 'Applied ML and model deployment for production systems.',
    minYearsExp: 6,
    maxYearsExp: 10,
    visaStatus: 'USC',
    employmentType: 'Full Time',
    workType: 'Remote',
    locations: 'Boston, MA',
    minRate: 75,
    maxRate: 120,
    relocationOpen: true,
    skills: 'Python, PyTorch, MLOps',
    scheduleFrequency: 'daily',
  },
  {
    id: 'security-engineer',
    title: 'Security Engineer',
    summary: 'Security operations and cloud protection for modern platforms.',
    minYearsExp: 5,
    maxYearsExp: 9,
    visaStatus: 'GC',
    employmentType: 'Full Time',
    workType: 'Hybrid',
    locations: 'Atlanta, GA',
    minRate: 70,
    maxRate: 110,
    relocationOpen: false,
    skills: 'Cloud Security, IAM, SOC',
    scheduleFrequency: 'weekly',
  },
  {
    id: 'solutions-architect',
    title: 'Solutions Architect',
    summary: 'Enterprise architecture and technical leadership across complex stacks.',
    minYearsExp: 8,
    maxYearsExp: 14,
    visaStatus: 'USC',
    employmentType: 'Full Time',
    workType: 'Remote',
    locations: 'Remote',
    minRate: 90,
    maxRate: 140,
    relocationOpen: true,
    skills: 'System Design, Cloud, Leadership',
    scheduleFrequency: 'daily',
  },
];
