import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Check, Loader2, Mail, Video, X } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { withScreeningLink } from '../lib/screening-link';

// Bulk sending is the reason people adopt this feature — nobody switches tools
// to send one email at a time. It is also the fastest way to get a user's own
// mailbox throttled, so three limits apply and all three are enforced on the
// server as well as shown here:
//
//   * Gmail must be connected. Sends leave from the user's own address.
//   * Trial 10 a day, paid 100 a day.
//   * 25 per run, under the daily cap, so nobody empties their quota in one
//     click and cannot react to the first replies before the rest go out.
//
// Sends run one at a time from the client rather than in a single edge
// function call: each draft is generated by a model and then delivered, so a
// batch of 25 would blow past the function's wall clock and fail as a unit,
// losing the ones that had already worked.
const PER_RUN_CAP = 25;

export type BulkTarget = {
  id: string;
  title: string;
  company: string;
  hasEmail: boolean;
  // Per target, not per feed. AI Match returns consultants to a vendor and
  // jobs to a bench sales user, and the combined feed can return both, so a
  // single feed-level flag mislabelled the action — a vendor matching
  // consultants was offered "AI Submit" when the action is an invite.
  kind: 'job' | 'hotlist';
};

type Quota = {
  used_today: number;
  daily_limit: number;
  remaining: number;
  is_trial: boolean;
  gmail_connected: boolean;
};

type Props = {
  targets: BulkTarget[];
  accountId: string;
  /**
   * The vendor's own job this match run came from, when there is one.
   * A screening link hangs off a job_applications row, which needs a job — a
   * run started from pasted text has none, so those invites go out as a plain
   * ask with no link rather than silently dropping the screening.
   */
  sourceJobId?: string | null;
  /** Tracked by the page already; the quota RPC is not the source of truth for it. */
  gmailConnected: boolean;
  /** True when the user has ticked specific cards rather than taking all of them. */
  isNarrowed?: boolean;
  onClearSelection?: () => void;
  onConnectGmail: () => void;
  onDone: () => void;
};

// Used until the quota RPC answers — and permanently if it is not deployed.
// Hiding the whole feature because a count is unavailable is worse than
// showing it with the conservative limit: the server enforces the real one on
// every send regardless of what this says.
const FALLBACK_QUOTA: Quota = {
  used_today: 0,
  daily_limit: 10,
  remaining: 10,
  is_trial: true,
  gmail_connected: false,
};

type Progress = { sent: number; failed: number; current: string } | null;

export default function BulkAiSubmitBar({ targets, accountId, sourceJobId, gmailConnected, isNarrowed, onClearSelection, onConnectGmail, onDone }: Props) {
  const [quota, setQuota] = useState<Quota>({ ...FALLBACK_QUOTA, gmail_connected: gmailConnected });
  const [confirming, setConfirming] = useState(false);
  const [progress, setProgress] = useState<Progress>(null);
  const [error, setError] = useState('');
  const [outlookRequested, setOutlookRequested] = useState(false);

  // Sending goes through the user's own Gmail, so everyone on Microsoft is
  // locked out entirely. Building Graph sending is a separate OAuth app and a
  // different send API — a real project — so this records who wants it and
  // lets the size of that queue decide, rather than guessing.
  async function requestOutlook() {
    setOutlookRequested(true);
    const { data: userData } = await supabase.auth.getUser();
    await supabase.from('platform_requests' as never).insert({
      account_id: accountId,
      user_id: userData?.user?.id ?? null,
      request_type: 'outlook_send',
    } as never);
  }

  const sendable = targets.filter((t) => t.hasEmail);
  // Label from what is actually in the batch. All consultants reads as an
  // invite, all jobs as a submit, and a mixed batch says neither rather than
  // picking one and being wrong half the time.
  const hotlistCount = sendable.filter((t) => t.kind === 'hotlist').length;
  const allHotlist = hotlistCount === sendable.length && sendable.length > 0;
  const allJobs = hotlistCount === 0 && sendable.length > 0;
  const label = allHotlist ? 'AI Invite' : allJobs ? 'AI Submit' : 'Send';
  const Icon = allHotlist ? Video : Mail;

  const loadQuota = useCallback(async () => {
    const { data, error: rpcError } = await supabase.rpc('get_ai_submit_quota' as never);
    if (rpcError) {
      // Not deployed, or unreachable. Keep the conservative fallback rather
      // than vanishing, and trust the page for the Gmail state.
      setQuota((current) => ({ ...current, gmail_connected: gmailConnected }));
      return;
    }
    const row = Array.isArray(data) ? data[0] : data;
    if (row) setQuota({ ...(row as Quota), gmail_connected: (row as Quota).gmail_connected || gmailConnected });
  }, [gmailConnected]);

  useEffect(() => { void loadQuota(); }, [loadQuota]);

  if (!sendable.length) return null;

  const batch = sendable.slice(0, Math.min(PER_RUN_CAP, quota.remaining));

  async function run() {
    setConfirming(false);
    setError('');
    let sent = 0;
    let failed = 0;

    for (const target of batch) {
      setProgress({ sent, failed, current: target.title });
      const requestId = crypto.randomUUID();
      try {
        const preview = await supabase.functions.invoke('ask-ai-vendor-email', {
          body: {
            action: 'preview',
            request_id: requestId,
            account_id: accountId,
            job_id: target.id,
            lead_type: target.kind,
            missing_details: target.kind === 'hotlist' ? ['video screening'] : ['Rate'],
          },
        });
        if (preview.error || !preview.data?.ok) throw new Error(preview.data?.error || 'draft failed');

        // An invite is only an invite if it carries the link. The draft is
        // appended to rather than replaced, so the AI's own wording for this
        // specific consultant survives.
        let emailContent = preview.data.email_content as string;
        if (target.kind === 'hotlist' && sourceJobId) {
          const { data: invite } = await supabase.rpc('invite_consultant_to_screening' as never, {
            p_social_job_id: sourceJobId,
            p_hotlist_id: target.id,
          } as never);
          const row = Array.isArray(invite) ? invite[0] : invite;
          const token = (row as { screening_token?: string } | null)?.screening_token;
          if (token) {
            emailContent = withScreeningLink(emailContent, `${window.location.origin}/screen/${token}`);
          }
        }

        const send = await supabase.functions.invoke('ask-ai-vendor-email', {
          body: {
            action: 'send',
            request_id: requestId,
            account_id: accountId,
            job_id: target.id,
            lead_type: target.kind,
            missing_details: target.kind === 'hotlist' ? ['video screening'] : ['Rate'],
            email_subject: preview.data.email_subject,
            email_content: emailContent,
            channel: 'gmail',
          },
        });
        if (send.error || !send.data?.ok) {
          // The server caps independently of this component. If it says stop,
          // stop — carrying on would burn credits on sends that cannot land.
          if (send.data?.error === 'daily_limit_reached') {
            setError(`Daily limit of ${send.data.daily_limit} reached. ${sent} sent.`);
            break;
          }
          throw new Error(send.data?.error || 'send failed');
        }
        sent += 1;
      } catch {
        failed += 1;
      }
    }

    setProgress(null);
    await loadQuota();
    onDone();
    if (!error) {
      setError(failed > 0 ? `${sent} sent, ${failed} could not be sent.` : '');
    }
  }

  if (!quota.gmail_connected) {
    return (
      <div className="mx-1.5 mb-2 overflow-hidden rounded-xl border border-amber-300 bg-amber-50">
        <div className="flex flex-wrap items-center gap-x-4 gap-y-2 px-4 py-3.5">
          <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-amber-100">
            <AlertTriangle size={17} className="text-amber-700" />
          </span>
          <div className="min-w-0 flex-1">
            <p className="text-[15px] font-semibold leading-tight text-amber-900">
              Connect Gmail to reach all {sendable.length} at once
            </p>
            <p className="mt-0.5 text-[12px] leading-tight text-amber-800/80">
              Sent from your own address, so replies come straight back to you.
            </p>
          </div>
          {outlookRequested ? (
            <span className="inline-flex items-center gap-1 text-[12px] font-medium text-amber-800">
              <Check size={13} /> Noted
            </span>
          ) : (
            <button
              onClick={() => void requestOutlook()}
              className="text-[12px] font-medium text-amber-800 underline underline-offset-2 hover:text-amber-900"
            >
              I use Outlook
            </button>
          )}
          <button
            onClick={onConnectGmail}
            className="shrink-0 rounded-lg bg-amber-600 px-5 py-2.5 text-[13px] font-bold text-white shadow-sm transition hover:bg-amber-700"
          >
            Connect Gmail
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="mx-1.5 mb-2 overflow-hidden rounded-xl bg-gradient-to-r from-indigo-600 to-blue-600 shadow-sm">
      {progress ? (
        <div className="px-4 py-3.5">
          <div className="flex items-center gap-2.5 text-white">
            <Loader2 size={16} className="animate-spin" />
            <span className="min-w-0 flex-1 truncate text-sm font-medium">
              Sending {progress.sent + progress.failed + 1} of {batch.length} — {progress.current}
            </span>
          </div>
          {/* A bar rather than a count: twenty-five sequential sends is long
              enough that a static number reads as frozen. */}
          <div className="mt-2 h-1 overflow-hidden rounded-full bg-white/25">
            <div
              className="h-full rounded-full bg-white transition-all duration-300"
              style={{ width: `${Math.round(((progress.sent + progress.failed) / Math.max(batch.length, 1)) * 100)}%` }}
            />
          </div>
        </div>
      ) : (
        <div className="flex flex-wrap items-center gap-x-4 gap-y-2 px-4 py-3.5">
          <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-white/15">
            <Icon size={17} className="text-white" />
          </span>

          <div className="min-w-0 flex-1">
            {/* No counts here. Credits, the daily limit and what will not fit
                today all belong on the confirm step, where someone is deciding
                whether to spend them — in the bar they were noise between the
                reader and the button. */}
            <p className="text-[15px] font-semibold leading-tight text-white">
              {isNarrowed
                ? `Send bulk invite to the ${batch.length} selected`
                : 'Send bulk invite to all matches'}
            </p>
            <p className="mt-0.5 text-[12px] leading-tight text-white/75">
              {isNarrowed ? 'Or clear the selection to send to everyone' : 'Or select below to choose who'}
            </p>
          </div>

          {isNarrowed && onClearSelection && (
            <button
              onClick={onClearSelection}
              className="text-[12px] font-medium text-white/70 underline underline-offset-2 hover:text-white"
            >
              Clear
            </button>
          )}

          <button
            onClick={() => setConfirming(true)}
            disabled={batch.length === 0}
            className="inline-flex shrink-0 items-center gap-2 rounded-lg bg-white px-5 py-2.5 text-[13px] font-bold text-indigo-700 shadow-sm transition hover:bg-indigo-50 disabled:cursor-not-allowed disabled:bg-white/40 disabled:text-white/70"
          >
            <Mail size={15} strokeWidth={2.25} />
            {batch.length === 0 ? 'Daily limit reached' : 'Send Now'}
          </button>
        </div>
      )}

      {error && (
        <p className="border-t border-white/20 bg-white/10 px-4 py-2 text-[12px] font-medium text-white">{error}</p>
      )}

      {confirming && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
          <div className="w-full max-w-sm rounded-lg bg-white p-4 shadow-xl dark:bg-slate-900">
            <div className="mb-2 flex items-start justify-between gap-2">
              <h3 className="text-sm font-semibold text-gray-900 dark:text-slate-100">
                {label} to {batch.length} match{batch.length === 1 ? '' : 'es'}?
              </h3>
              <button onClick={() => setConfirming(false)} className="text-gray-400 hover:text-gray-600">
                <X size={15} />
              </button>
            </div>
            <ul className="mb-3 space-y-1 text-[11px] text-gray-600 dark:text-slate-300">
              <li>· Each one costs 1 credit — <b>{batch.length} credits</b> in total.</li>
              {sendable.length > batch.length && (
                <li>· <b>{sendable.length - batch.length}</b> will not fit today and can go tomorrow.</li>
              )}
              <li>· Sent from your connected Gmail, one at a time.</li>
              <li>· Every message is written for that specific post, not a template.</li>
              <li>· You will have <b>{Math.max(0, quota.remaining - batch.length)}</b> sends left today.</li>
            </ul>
            <div className="flex gap-2">
              <button
                onClick={() => setConfirming(false)}
                className="flex-1 rounded-md border border-gray-300 py-2 text-xs font-semibold text-gray-700 hover:bg-gray-50 dark:border-slate-600 dark:text-slate-200"
              >
                Cancel
              </button>
              <button
                onClick={() => void run()}
                className="flex-1 rounded-md bg-blue-600 py-2 text-xs font-semibold text-white hover:bg-blue-700"
              >
                Send {batch.length}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
