import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Loader2, Mail, Video, X } from 'lucide-react';
import { supabase } from '../lib/supabase';

// Bulk sending is the reason people adopt this feature — nobody switches tools
// to send one email at a time. It is also the fastest way to get a user's own
// mailbox throttled, so three limits apply and all three are enforced on the
// server as well as shown here:
//
//   * Gmail must be connected. Sends leave from the user's own address.
//   * Trial 10 a day, paid 100 a day.
//   * 25 per run, under the daily cap, so nobody empties their quota in one
//     click and cannot react to the first replies before the rest go out.
//
// Sends run one at a time from the client rather than in a single edge
// function call: each draft is generated by a model and then delivered, so a
// batch of 25 would blow past the function's wall clock and fail as a unit,
// losing the ones that had already worked.
const PER_RUN_CAP = 25;

export type BulkTarget = {
  id: string;
  title: string;
  company: string;
  hasEmail: boolean;
};

type Quota = {
  used_today: number;
  daily_limit: number;
  remaining: number;
  is_trial: boolean;
  gmail_connected: boolean;
};

type Props = {
  targets: BulkTarget[];
  leadType: 'job' | 'hotlist';
  accountId: string;
  /** Tracked by the page already; the quota RPC is not the source of truth for it. */
  gmailConnected: boolean;
  onConnectGmail: () => void;
  onDone: () => void;
};

// Used until the quota RPC answers — and permanently if it is not deployed.
// Hiding the whole feature because a count is unavailable is worse than
// showing it with the conservative limit: the server enforces the real one on
// every send regardless of what this says.
const FALLBACK_QUOTA: Quota = {
  used_today: 0,
  daily_limit: 10,
  remaining: 10,
  is_trial: true,
  gmail_connected: false,
};

type Progress = { sent: number; failed: number; current: string } | null;

export default function BulkAiSubmitBar({ targets, leadType, accountId, gmailConnected, onConnectGmail, onDone }: Props) {
  const [quota, setQuota] = useState<Quota>({ ...FALLBACK_QUOTA, gmail_connected: gmailConnected });
  const [confirming, setConfirming] = useState(false);
  const [progress, setProgress] = useState<Progress>(null);
  const [error, setError] = useState('');

  const sendable = targets.filter((t) => t.hasEmail);
  const label = leadType === 'hotlist' ? 'AI Invite' : 'AI Submit';
  const Icon = leadType === 'hotlist' ? Video : Mail;

  const loadQuota = useCallback(async () => {
    const { data, error: rpcError } = await supabase.rpc('get_ai_submit_quota' as never);
    if (rpcError) {
      // Not deployed, or unreachable. Keep the conservative fallback rather
      // than vanishing, and trust the page for the Gmail state.
      setQuota((current) => ({ ...current, gmail_connected: gmailConnected }));
      return;
    }
    const row = Array.isArray(data) ? data[0] : data;
    if (row) setQuota({ ...(row as Quota), gmail_connected: (row as Quota).gmail_connected || gmailConnected });
  }, [gmailConnected]);

  useEffect(() => { void loadQuota(); }, [loadQuota]);

  if (!sendable.length) return null;

  const batch = sendable.slice(0, Math.min(PER_RUN_CAP, quota.remaining));

  async function run() {
    setConfirming(false);
    setError('');
    let sent = 0;
    let failed = 0;

    for (const target of batch) {
      setProgress({ sent, failed, current: target.title });
      const requestId = crypto.randomUUID();
      try {
        const preview = await supabase.functions.invoke('ask-ai-vendor-email', {
          body: {
            action: 'preview',
            request_id: requestId,
            account_id: accountId,
            job_id: target.id,
            lead_type: leadType,
            missing_details: leadType === 'hotlist' ? ['video screening'] : ['Rate'],
          },
        });
        if (preview.error || !preview.data?.ok) throw new Error(preview.data?.error || 'draft failed');

        const send = await supabase.functions.invoke('ask-ai-vendor-email', {
          body: {
            action: 'send',
            request_id: requestId,
            account_id: accountId,
            job_id: target.id,
            lead_type: leadType,
            missing_details: leadType === 'hotlist' ? ['video screening'] : ['Rate'],
            email_subject: preview.data.email_subject,
            email_content: preview.data.email_content,
            channel: 'gmail',
          },
        });
        if (send.error || !send.data?.ok) {
          // The server caps independently of this component. If it says stop,
          // stop — carrying on would burn credits on sends that cannot land.
          if (send.data?.error === 'daily_limit_reached') {
            setError(`Daily limit of ${send.data.daily_limit} reached. ${sent} sent.`);
            break;
          }
          throw new Error(send.data?.error || 'send failed');
        }
        sent += 1;
      } catch {
        failed += 1;
      }
    }

    setProgress(null);
    await loadQuota();
    onDone();
    if (!error) {
      setError(failed > 0 ? `${sent} sent, ${failed} could not be sent.` : '');
    }
  }

  if (!quota.gmail_connected) {
    return (
      <div className="mx-1.5 mb-2 flex items-start gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">
        <AlertTriangle size={14} className="mt-0.5 shrink-0" />
        <div className="min-w-0 flex-1">
          <p className="font-semibold">Connect Gmail to send to all {sendable.length} matches at once.</p>
          <p className="mt-0.5">Messages go from your own address, so replies come straight back to you.</p>
          <button
            onClick={onConnectGmail}
            className="mt-2 rounded-md bg-amber-600 px-3 py-1.5 text-[11px] font-semibold text-white hover:bg-amber-700"
          >
            Connect Gmail
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="mx-1.5 mb-2 rounded-lg border border-blue-200 bg-blue-50 p-3 dark:border-blue-500/30 dark:bg-blue-500/10">
      {progress ? (
        <div className="flex items-center gap-2 text-xs text-blue-900 dark:text-blue-200">
          <Loader2 size={14} className="animate-spin" />
          <span className="min-w-0 flex-1 truncate">
            Sending {progress.sent + progress.failed + 1} of {batch.length} — {progress.current}
          </span>
        </div>
      ) : (
        <div className="flex flex-wrap items-center gap-2">
          <Icon size={15} className="shrink-0 text-blue-600 dark:text-blue-400" />
          <div className="min-w-0 flex-1">
            <p className="text-xs font-semibold text-blue-900 dark:text-blue-200">
              {label} to all {batch.length} match{batch.length === 1 ? '' : 'es'}
            </p>
            <p className="text-[11px] text-blue-700/80 dark:text-blue-300/80">
              {quota.remaining} of {quota.daily_limit} left today
              {quota.is_trial && ' on the trial plan'}
              {sendable.length > batch.length && ` · ${sendable.length - batch.length} will not fit today`}
            </p>
          </div>
          <button
            onClick={() => setConfirming(true)}
            disabled={batch.length === 0}
            className="rounded-md bg-blue-600 px-3 py-1.5 text-[11px] font-semibold text-white transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:bg-gray-300"
          >
            {batch.length === 0 ? 'Daily limit reached' : `Send ${batch.length}`}
          </button>
        </div>
      )}

      {error && <p className="mt-2 text-[11px] font-medium text-red-600">{error}</p>}

      {confirming && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
          <div className="w-full max-w-sm rounded-lg bg-white p-4 shadow-xl dark:bg-slate-900">
            <div className="mb-2 flex items-start justify-between gap-2">
              <h3 className="text-sm font-semibold text-gray-900 dark:text-slate-100">
                {label} to {batch.length} match{batch.length === 1 ? '' : 'es'}?
              </h3>
              <button onClick={() => setConfirming(false)} className="text-gray-400 hover:text-gray-600">
                <X size={15} />
              </button>
            </div>
            <ul className="mb-3 space-y-1 text-[11px] text-gray-600 dark:text-slate-300">
              <li>· Each one costs 1 credit — <b>{batch.length} credits</b> in total.</li>
              <li>· Sent from your connected Gmail, one at a time.</li>
              <li>· Every message is written for that specific post, not a template.</li>
              <li>· You will have <b>{Math.max(0, quota.remaining - batch.length)}</b> sends left today.</li>
            </ul>
            <div className="flex gap-2">
              <button
                onClick={() => setConfirming(false)}
                className="flex-1 rounded-md border border-gray-300 py-2 text-xs font-semibold text-gray-700 hover:bg-gray-50 dark:border-slate-600 dark:text-slate-200"
              >
                Cancel
              </button>
              <button
                onClick={() => void run()}
                className="flex-1 rounded-md bg-blue-600 py-2 text-xs font-semibold text-white hover:bg-blue-700"
              >
                Send {batch.length}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
