#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DOC_FILE="$ROOT_DIR/docs/profilepush-platform-documentation.md"
BACKUP_DIR="$ROOT_DIR/docs/backups"
APP_FILE="$ROOT_DIR/src/App.tsx"
FUNCTIONS_DIR="$ROOT_DIR/supabase/functions"

if [[ ! -f "$DOC_FILE" ]]; then
  echo "Documentation file not found: $DOC_FILE" >&2
  exit 1
fi

if [[ ! -f "$APP_FILE" ]]; then
  echo "App route file not found: $APP_FILE" >&2
  exit 1
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

ROUTES_FILE="$TMP_DIR/routes.txt"
FRONTEND_ENV_FILE="$TMP_DIR/frontend_env.txt"
BACKEND_ENV_FILE="$TMP_DIR/backend_env.txt"
FUNCTION_MAP_FILE="$TMP_DIR/function_map.txt"
BLOCK_FILE="$TMP_DIR/block.md"

mkdir -p "$BACKUP_DIR"
BACKUP_FILE="$BACKUP_DIR/profilepush-platform-documentation-$(date -u +"%Y%m%d-%H%M%S").txt"
cp "$DOC_FILE" "$BACKUP_FILE"

awk '
/\{\/\* Public \*\/\}/ { section = "public"; next }
/\{\/\* Protected \*\/\}/ { section = "protected"; next }
/Route path="/ {
  if (match($0, /path="[^"]+"/)) {
    path_token = substr($0, RSTART + 6, RLENGTH - 7);
    if (section == "") section = "unknown";
    print section "|" path_token;
  }
}
' "$APP_FILE" | sort > "$ROUTES_FILE"

find "$ROOT_DIR/src" -type f \( -name "*.ts" -o -name "*.tsx" \) -print0 \
  | xargs -0 grep -ho 'import\.meta\.env\.[A-Z0-9_]*' \
  | sed -E 's/.*\.([A-Z0-9_]+)$/\1/' \
  | sort -u > "$FRONTEND_ENV_FILE"

find "$FUNCTIONS_DIR" -type f -name "*.ts" -print0 \
  | xargs -0 grep -ho 'Deno\.env\.get("[A-Z0-9_]*")' \
  | sed -E 's/.*"([A-Z0-9_]+)".*/\1/' \
  | sort -u > "$BACKEND_ENV_FILE"

for f in "$FUNCTIONS_DIR"/*/index.ts; do
  fn="$(basename "$(dirname "$f")")"
  envs="$(grep -ho 'Deno\.env\.get("[A-Z0-9_]*")' "$f" \
    | sed -E 's/.*"([A-Z0-9_]+)".*/\1/' \
    | sort -u \
    | tr '\n' ',' \
    | sed 's/,$//')"
  if [[ -z "$envs" ]]; then
    envs="none"
  fi
  echo "$fn|$envs"
done | sort > "$FUNCTION_MAP_FILE"

SYNC_TIME="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"

{
  echo "<!-- AUTO-GENERATED:START -->"
  echo "## 12) Auto-Sync Snapshot"
  echo
  echo "Last synced: $SYNC_TIME"
  echo
  echo "This section is generated by scripts/update-platform-doc.sh."
  echo
  echo "### 12.1 Route Snapshot"
  echo
  echo "Public routes:"
  grep '^public|' "$ROUTES_FILE" | sed -E 's/^public\|/- /'
  echo
  echo "Protected routes:"
  grep '^protected|' "$ROUTES_FILE" | sed -E 's/^protected\|/- /'
  echo
  echo "### 12.2 Frontend Environment Variables"
  echo
  sed -E 's/^/- /' "$FRONTEND_ENV_FILE"
  echo
  echo "### 12.3 Backend Environment Variables"
  echo
  sed -E 's/^/- /' "$BACKEND_ENV_FILE"
  echo
  echo "### 12.4 Edge Function To Env Mapping"
  echo
  while IFS='|' read -r fn envs; do
    echo "- $fn: $envs"
  done < "$FUNCTION_MAP_FILE"
  echo
  echo "<!-- AUTO-GENERATED:END -->"
} > "$BLOCK_FILE"

if grep -q "<!-- AUTO-GENERATED:START -->" "$DOC_FILE"; then
  awk -v block_file="$BLOCK_FILE" '
  BEGIN {
    while ((getline line < block_file) > 0) {
      block[++n] = line;
    }
    close(block_file);
  }
  /<!-- AUTO-GENERATED:START -->/ {
    in_block = 1;
    for (i = 1; i <= n; i++) print block[i];
    next;
  }
  /<!-- AUTO-GENERATED:END -->/ {
    in_block = 0;
    next;
  }
  !in_block { print }
  ' "$DOC_FILE" > "$DOC_FILE.tmp"
  mv "$DOC_FILE.tmp" "$DOC_FILE"
else
  printf "\n\n" >> "$DOC_FILE"
  cat "$BLOCK_FILE" >> "$DOC_FILE"
fi

echo "Saved backup to $BACKUP_FILE"
echo "Updated documentation snapshot in $DOC_FILE"
