-- Stores AI-drafted outreach comments generated by the /admin Post
-- Outreach panel — one row per scraped post, written by the
-- admin-post-outreach Cloudflare Worker's queue consumer, polled by the
-- frontend via the admin-posts edge function.
create table if not exists public.admin_post_comments (
  post_id uuid primary key,
  kind text not null check (kind in ('job', 'hotlist')),
  comment text,
  matching_count integer,
  status text not null default 'pending' check (status in ('pending', 'done', 'failed')),
  generated_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.admin_post_comments enable row level security;

-- Deliberately no grants to authenticated/anon and no policies: only the
-- service role (via the admin-post-outreach worker) ever touches this.
grant select, insert, update on public.admin_post_comments to service_role;
